/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/jacket.glb -T 
Files: public/models/jacket.glb [13.12MB] > C:\Users\Studio\Desktop\GorillaBullys\Web3Webflow\jacket-transformed.glb [1.88MB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jacket(props) {
  const { nodes, materials } = useGLTF('https://master--effortless-caramel-ffd67a.netlify.app/models/jacket.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.JacketOpenNoTextures004.geometry} material={materials['Material.023']} />
    </group>
  )
}

useGLTF.preload('https://master--effortless-caramel-ffd67a.netlify.app/models/jacket.glb')
